### ISSUE TITLE
Min/Max Brightness setting

### ISSUE THREAD

**Issue by brindosch** [mookfist/repo#15]
First of all, big thank you for this plugin.

I have a question regarding to this setting. In my case, this setting won´t function as it´s supposed to be?! Set a min and max brightness to fadeIn and fadeOut? You mentioned nothing about it here and in the kodi forum. Something i am not understood?

And if you want a german language string i could provide one.

Thank you mookfist

**Comment by mookfist** [comment]
Hello, I am glad you find the plugin useful. If you wish to submit a german language file, I am more than happy to accept it. Might even help me learn a bit of german too. This should be handled by a separate issue however. I will open one now.

As for the min and max brightness levels, I do not believe they are fully supported yet. If there isn't an open issue for this yet, I will create one immediately and try to add it in later on tonight. Basically, the functionality would be:

Max brightness will also be the initial brightness when the plugin starts

Fading will go from Max to Min brightness and back again.

Also note, this plugin should be considered "beta" until the 0.1.0 milestone is fully reached.

**Comment by mookfist** [comment]
I've opened issue #17 for german localization, as well as tasks for spanish and french localizations.

**Comment by brindosch** [comment]
"Max brightness will also be the initial brightness when the plugin starts" -> yes that is right
"Fading will go from Max to Min brightness and back again" -> the first fadeOff it will dimm to the minimal brightness that is possible (the min bright setting won´t function at the moment) after this, it is fadeOn to the max brightness that is possible (ignores the max bright setting now)

But the initial brightness on startup and the nice dimm to the lowest level is working fine

**Comment by mookfist** [comment]
new version is in, and it should be respecting the min and max brightness. Closing ticket, but re-open it if you encounter any errors.

As well, I've added a new ability to turn on and off logging, and it is turned off by default. If you turn it on and look at your kodi log, you will see all the actions the plugin is taking to control your lights. This will help debug any potential issues.

**Comment by brindosch** [comment]
You are faster than light! Great integration but i found a little bug.
Everey time you activate/deactivate or change a setting (should be the "same" now) only the first  fadeOff is instant.
