### ISSUE TITLE
[enhancement] Load changed setting immediately

### ISSUE THREAD

**Issue by brindosch** [mookfist/repo#16]
At the moment you have to restart Kodi for changes to take effect.
Additional if you want to deactivate the plugin it freezes (to active it again to load changed settings without a kodi restart)

**Comment by mookfist** [comment]
I've actually gotten so used to disable/enable after I make changes, I completely forgot about this ;)

I have not encountered any freezing issues however. Can you better explain what is happening and perhaps include some kodi log files?

thanks

**Comment by brindosch** [comment]
I have a problem, can´t reproduce it -.-. Will have a look on this.

**Comment by mookfist** [comment]
the new version is in. The service does not need to be restarted any longer when you change configuration. Closing ticket, but if you encounter any problems feel free to re-open the issue.
