### ISSUE TITLE
Localization - German (DE)

### ISSUE THREAD

**Issue by mookfist** [mookfist/repo#17]
Add localized string resource files for german

**Comment by mookfist** [comment]
a native german speaker is needed for this ;)

**Comment by brindosch** [comment]
Here it is, please rename it back to .po the github upload don´t want .po files. Sad that i am not familiar with the github system.
[strings.txt](https://github.com/mookfist/repo/files/57311/strings.txt)

I also have a description and disclaimer for your addon.xml (just translated and little bit extended)


<description lang="de">Steuert LimitlessLED kompatible Produkte (Milight / LimitlessLED / Easybulb / AppLamp / iLight) mithilfe des WLAN Steuermoduls (Bridge)</description>
  
  <disclaimer lang="de">Kann Spuren von Soja enthalten</disclaimer>

**Comment by mookfist** [comment]
Many thanks for the pull request. As soon as I'm finished with my latest batch of changes for v0.0.11 I'll merge the pull request for it.

**Comment by mookfist** [comment]
The pull request is merged. thanks again for your help!
