### ISSUE TITLE
Early fade up

### ISSUE THREAD

**Issue by smartroad** [mookfist/repo#23]
Hi!
Just getting started with this and it is great! Would it be possible to have the lights come back up a while before the end of the video? Adjustable for TV shows and movies. Just thinking when watching a movie the lights often come back up about 50% while the credits run. Although there is no way to detect when the credits roll (I guess there is no way to detect) could there be an option to have the lights come back a user adjustable time, independent controls for TV and Movie?

Cheers for writing this it is awesome to have the lights come back up as the program finishes!

**Comment by mookfist** [comment]
Sorry for the late reply. I have been very busy and have not had much spare time.

I don't really know if it would be possible to determine when exactly the credits will start, but it's easy to figure out the length of the video currently playing.

So I can provide the option of fading the lights a configurable number of settings from the video ending. Unfortunately though, this won't work great with TV shows when tend not to have credits, and if you're binge watching, you may not want this. So this has to be a toggable feature per TV and Movie.

**Comment by mookfist** [comment]
In v0.2.0 all settings will be exposed for tweaking.
