### ISSUE TITLE
lights.off() not implemented?

### ISSUE THREAD

**Issue by johnwillson** [mookfist/repo#28]
Trying to add some Time of Day features to this add on (i.e. sunset/sunrise), but the ability to turn off the lights doesn't appear to be implemented in lights.py.

Not really a programmer here, so let me know if I'm missing something.

**Comment by mookfist** [comment]
With the v0.2.0 of this plugin, there are now ways of integrating against this plugin using notifications or plugin actions.

on, off, color_rgb, fade in, fade out, white commands are currently supported. Refer to the README in the 0.2.0devel branch for more information or stay tuned for 0.2.0 being pushed to the master branch.
