### ISSUE TITLE
Allow user to select fading speed

### ISSUE THREAD

**Issue by mookfist** [mookfist/repo#4]
Dimming is done manually rather than using the native fadeIn/fadeOut commands. Thus I should be able to have some degree of control over the speed.

Since it's not perfect, I'll offer three options only:

fast, normal, slow.

**Comment by jacaba1** [comment]
Fast is very slow,

How I can change the speed?

**Comment by mookfist** [comment]
The feature hasn't been fully implemented yet.

I do plan on looking into it tonight however and hope to close this issue by next week.

If you're unwilling to wait and want to hack the code yourself, in file light.py there are two methods, fadeOn and fadeOff. You can tweak these methods to change the speed of fading.

**Comment by mookfist** [comment]
there is osmething else that needs mentioning:

Fading speed is done by sending commands to change the brightness level. Because of how Limitless LED protocol works, speeds will always be... inconsistent. Sometimes commands will get dropped. And there is a limit to how fast commands can be broadcast from the wifi dongle to the bulbs themselves. I believe the recommended limit is 100ms.

As well, fading is done through percentages. So the speed of fading will be less based on how fast I can iterate over a loop of numbers from 0 to 100, and instead be more based on how many steps I take to get from 0 to 100 or vice versa.

So for example, a "fast" speed might mean doing 100-80-60-40-20-0, a normal speed might be 100-90-80-70-60-50-40-30-20-10-0 and a slow speed might be 100-95-90-85-80-75-70-65-60-55-50-45-40-35-30-25-20-15-10-5-0

with the commands sent as fast as they can be sent.

This is a limitation of the LimitlessLED protocol and I can't work around that. That said, I will open a new issue, to expose the native LimitlessLED fading command. In my experiments with my own bulbs, I have found the fading command to be not very reliable, but I'll expose it anyways in case it works better for others.

**Comment by mookfist** [comment]
a new version has been put out, version 0.0.8.

The configuration has changed considerably. Under the Global settings, you will see a new speed setting with slow, medium, fast, and immediate and they are now respected.

Let me know if you have any problems with the functionality.

**Comment by mookfist** [comment]
So finally:

Immediate decreases brightness 100% once
Fast speed decreases brightness 20% five times
Medium speed decreases brightness by 10% ten times
Slow speed decreases brightness by 1% one hundred times

There is minimum limit of 25ms between brightness commands sent to the bulb. Sometimes it could be longer. There is a new issue open to allow this minimum limit to be configurable.

**Comment by jacaba1** [comment]
hello, How's the project?
I tried the dimmer group and it is fantastic but not working group 4.
For me it is no problem, however, I would like it to work the dimmer to pause

regard

**Comment by mookfist** [comment]
Hello, sorry for the late reply. I have been very busy lately.

I have fixed the issue for Group 4 as well as add some controls for pausing.
